### ISSUE TITLE
Peer review RegistrationApp

### ISSUE THREAD

**Issue by em222iv** [vl222cu/1DV450_vl222cu_RegistrationApp#1]
Hej Vivi!

Jag har gått igenom ditt app och tycker det ser bra ut.

Installationen var lite krånglig då varken "rails s" eller ditt förslag på " rails server -b 0.0.0.0" fungerade.
Jag lyfte in secret.yml filen från ett annat projekt så fungerade det fint på localhost!

Eftersom jag inte kan så mycket om rails(än) så har jag svårt att bedöma kodkvalité.
Detta är endast ett personligt utlåtande, och behöver inte alls säga att det är det bättre/sämre.

Men jag eftersom du brutit ut user och admin till olika controlrar så blir det lite upprepning.
Det skulle gå att göra i samma controller och bara lösa skillnaderna med If-satser.

Det kan ju dock ses som lite tydligare när det är uppbrutet till olika controlrar, vilket kan vara bra!

Som sagt, appen fungerar bra och jag hoppas du mår bra i övrigt!

Mvh,
Erik Magnusson
em222iv

**Comment by vl222cu** [comment]
Hej Erik!

Tack så mycket för din feedback! :) OK, vad bra att du löste det ändå trots att mina instruktioner inte funkade. Jag hade också väldans problem med att få igång rails server men det förslaget jag skrev med där funkade bra hos mig i Nitrous så trodde att det skulle lösa allas problem om det blev krångel med localhost men så var det ju inte! Då vet jag iaf att man även kan behöva använda sig av secret.yml-filen, ska lägga till det i instruktionerna :) 

Mm jag håller med dig om att det finns både för -och nackdelar att ha det som jag gjort det men ja, jag är också ny på rails så jag tar absolut med mig ditt utlåtande för du har helt rätt om att det blev lite upprepning där mellan user o admin samt att if-satser säkert kan lösa det med mindre kod :) 

Jo tack, jag mår bara fint, hoppas allt är bra med dig också :) Ha det gott!

Hälsningar Vivi

**Comment by 1dv450** [comment]
Vad det gäller secret.yml så är den spärrad av .gitignore. Man vill inte skicka upp den till github då den innehåller hashningar man inte vill ska läcka. Dock kanske det spelar mindre roll för development och test. Men oftast bruka rman få kopiera in en egen sådan.
