### ISSUE TITLE
ms223eq

### ISSUE THREAD

**Issue by latana** [vl222cu/1DV450_vl222cu_RegistrationApp#2]
Hejsan!

Din kod ser fin och välkonstruerad ut! Det var riktigt lätt att titta igenom den. Dock saknade jag lite kommentarer men ruby är ganska lättläst så det kanske var ett medvetet val.
1. En användare kan skriva in "/admin_show" och se alla användares apinycklar. Användaren kan även ta bort andra användare.
2. Många av dina before_action pekar på metoder som inte finns. Detta kanske är anledningen till att punkt 1 inte funkar. Jag tänker främst på filerna users_controller och admins_controller. En lösning är kanske att bara skriva "before_action :check_admin". Ingen metod ska kunna användas förutom admin oavsett. Funkar det annars för dig? Är det kanske jag som tagit sönder någon när jag krånglade lokalt?
3. Admin har en egen login. Skulle man inte kunna slå ihop admin login med user login?

Annars ser det riktigt bra ut. Snyggt jobbat!

MVH Måns Schütz

**Comment by vl222cu** [comment]
Hej Måns!

Tack så jättemycket för din feedback! :) Ja, just med kommentarerna så tänkte jag att det kanske blir lite överflödigt då variablernas -och metodernas namn talar lite för sig själva men ja, kommentarer är ju annars bra att ha med :) 
1. Ojoj, den delen testade jag inte alls, tänkte inte ens på att man kunde gå den vägen så det var bra att du upptäckte säkerhetshålet, tack! :) 
2. Hm, tänkte du just på check_admin och check_user som finns med i mina before_action eller det som står efter check_admin resp check_user med only [:delete] etc? När det gäller just mina check_user och check_admin så ligger dessa metoder i mina helpers, sessionshelpers resp adminshelpers men ja, just det som står efter only ställer ju till detta fel så ska fixa det :) Gick inte så bra att bara ha before_action :check_admin för då kunde jag inte logga in som Admin alls, kanske mina routes som är helt uppåt väggarna :/ 
3. Jo, det går säkert att använda samma inloggningsformulär för admin och user, det har du rätt i :) Jag har slaviskt följt Johns instruktioner för appen till punkt och pricka just då han skriver i uppgiftsbeskrivningen "Inloggningsformulär för en administratör" haha :) Tolkade det som att det skulle finnas 2 formulärer, en för användare och en för administratör :) Får bli en todo-förbättringslist och ta det vid ett senare tillfälle när det finns tid över, om nu inte John absolut kräver att jag ska ändra för att få godkänt dvs :P 

Tack så jättemycket än en gång för din feedback, glad jag blir att höra att min kod ser fin ut då jag aldrig kodat i Rubys nånsin :) 

Hoppas allt går bra för dig med alla uppgifter och projekt :) 

Hälsningar Vivi

**Comment by 1dv450** [comment]
Mycket bra feedback och viktigt att fixa till säkerhetshålen! Framförallt är det viktigt att ta till sig att alltid kontrollera sådana saker noga!

Vad det gäller formulären så visst skrev jag så sätt men det är ju inget som utesluter att ha ett och samma formulär som båda rollerna använder. I denna uppgift kanske detta varit att föredra. Och nej, inget jag kräver du ändrar. Det är mer ett designval. Ibland kanske man vill ha en tydlig userdel och en tydlig admindel som mer uppdelade applikationer.

Punkt 2, så ligger som sagt dina metoder för dessa i sessionhelper. Men only talar om vilka metoder som ska skyddas. Du bör gå igenom dessa för Admin- och Usercontrollern!
